#!/usr/bin/env python
# PHDL HDLWriter

import Dev
import HDLNetType

class HDLWriter:
	def __init__(self):
		Dev.Debug(Dev.Info,"HDLWriter.__init__(self)")

	def Open(self,str):
		Dev.Debug(Dev.Info,"HDLWriter.Open(self,str)")
		self.outfile = open(str,’w+’)
		self.Write("// Autogenerated by PHDL\n\n");

	def Close(self):
		Dev.Debug(Dev.Info,"HDLWriter.Close(self)")
		self.outfile.close()

	def Write(self,str):
		Dev.Debug(Dev.Info,"HDLWriter.Write(self,str)")
		self.outfile.write(str)

	def WriteModule(self,module):
		Dev.Debug(Dev.Error,"HDLWriter.WriteModule(self,module) ERROR NOT IMPLEMENTED")
